require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TicketActionsController do

  # This should return the minimal set of attributes required to create a valid
  # TicketAction. As you add validations to TicketAction, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "comment" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TicketActionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ticket_actions as @ticket_actions" do
      ticket_action = TicketAction.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ticket_actions).should eq([ticket_action])
    end
  end

  describe "GET show" do
    it "assigns the requested ticket_action as @ticket_action" do
      ticket_action = TicketAction.create! valid_attributes
      get :show, {:id => ticket_action.to_param}, valid_session
      assigns(:ticket_action).should eq(ticket_action)
    end
  end

  describe "GET new" do
    it "assigns a new ticket_action as @ticket_action" do
      get :new, {}, valid_session
      assigns(:ticket_action).should be_a_new(TicketAction)
    end
  end

  describe "GET edit" do
    it "assigns the requested ticket_action as @ticket_action" do
      ticket_action = TicketAction.create! valid_attributes
      get :edit, {:id => ticket_action.to_param}, valid_session
      assigns(:ticket_action).should eq(ticket_action)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TicketAction" do
        expect {
          post :create, {:ticket_action => valid_attributes}, valid_session
        }.to change(TicketAction, :count).by(1)
      end

      it "assigns a newly created ticket_action as @ticket_action" do
        post :create, {:ticket_action => valid_attributes}, valid_session
        assigns(:ticket_action).should be_a(TicketAction)
        assigns(:ticket_action).should be_persisted
      end

      it "redirects to the created ticket_action" do
        post :create, {:ticket_action => valid_attributes}, valid_session
        response.should redirect_to(TicketAction.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ticket_action as @ticket_action" do
        # Trigger the behavior that occurs when invalid params are submitted
        TicketAction.any_instance.stub(:save).and_return(false)
        post :create, {:ticket_action => { "comment" => "invalid value" }}, valid_session
        assigns(:ticket_action).should be_a_new(TicketAction)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TicketAction.any_instance.stub(:save).and_return(false)
        post :create, {:ticket_action => { "comment" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ticket_action" do
        ticket_action = TicketAction.create! valid_attributes
        # Assuming there are no other ticket_actions in the database, this
        # specifies that the TicketAction created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TicketAction.any_instance.should_receive(:update_attributes).with({ "comment" => "MyString" })
        put :update, {:id => ticket_action.to_param, :ticket_action => { "comment" => "MyString" }}, valid_session
      end

      it "assigns the requested ticket_action as @ticket_action" do
        ticket_action = TicketAction.create! valid_attributes
        put :update, {:id => ticket_action.to_param, :ticket_action => valid_attributes}, valid_session
        assigns(:ticket_action).should eq(ticket_action)
      end

      it "redirects to the ticket_action" do
        ticket_action = TicketAction.create! valid_attributes
        put :update, {:id => ticket_action.to_param, :ticket_action => valid_attributes}, valid_session
        response.should redirect_to(ticket_action)
      end
    end

    describe "with invalid params" do
      it "assigns the ticket_action as @ticket_action" do
        ticket_action = TicketAction.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TicketAction.any_instance.stub(:save).and_return(false)
        put :update, {:id => ticket_action.to_param, :ticket_action => { "comment" => "invalid value" }}, valid_session
        assigns(:ticket_action).should eq(ticket_action)
      end

      it "re-renders the 'edit' template" do
        ticket_action = TicketAction.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TicketAction.any_instance.stub(:save).and_return(false)
        put :update, {:id => ticket_action.to_param, :ticket_action => { "comment" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ticket_action" do
      ticket_action = TicketAction.create! valid_attributes
      expect {
        delete :destroy, {:id => ticket_action.to_param}, valid_session
      }.to change(TicketAction, :count).by(-1)
    end

    it "redirects to the ticket_actions list" do
      ticket_action = TicketAction.create! valid_attributes
      delete :destroy, {:id => ticket_action.to_param}, valid_session
      response.should redirect_to(ticket_actions_url)
    end
  end

end
